### ISSUE TITLE
define config file for multiple image downloads and unpacking

### ISSUE THREAD

**Issue by maxwellflitton** [maxwellflitton/dockpack#6]
As `dockpack` downloads and unpacks files from Docker images, we should enable users to create a config file for `dockpack` to read and download a collection of images and unpack them, like a generic package manager. Here we need to agree on fields and layout of a `dockpack`    config file. After this, we can build the mechanism of reading and unpacking a list of these. I'll start by suggesting that the config file could take the following:

```yaml
version: "1.0"
directory: "/path/to/your/project"
bucket_name: "bucket A"
docker_images:
  - name: "image1:tag1"
  - name: "image2:tag2"
  - name: "image3:tag3"
```
In later versions, we can be a bit more advanced but I think this is good enough to be useful. The `bucket` concept just refers to a collection of images to be downloaded. I think we can also override the `directory` field in the command that is reading the config file.
